language: go

go:
  - "1.14.x"

branches:
  only:
#    - master
    - dev
env:
  - GO111MODULE=on
install: true
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go list ./... | grep -v worker | xargs go vet
  - cat tools/cover.txt | xargs go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN